apiVersion: v1
kind: Pod
metadata:
  name: deepvariant-benchmark
  labels:
    name: deepvariant-benchmark
spec:
  containers:
  - name: deepvariant-benchmark
    image: google/deepvariant:1.3.0-gpu
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "sleep 36500000"]
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: OnFailure
  
